### ISSUE TITLE
jsnext:main in webpack

### ISSUE THREAD

**Issue by sokra** [jthoms1/tree-shake-me#1]
packageMains are trled in order. So if you want jsnext to take priority over main you need to put in before main in the array.

**Comment by jthoms1** [comment]
Thanks for opening this issue and offering guidance! I had tried this, but it appeared not to work.  I was given some guidance about using "mainFields" in place of "packageMains" and everything started working. 37176e296d200c301fe613407bcd535e1c893a3d

**Comment by sokra** [comment]
oh yes :smile: 

https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options
